services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=epl_predictions
    restart: always
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - external-network
      - internal-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - external-network
      - internal-network

networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true

volumes:
  postgres-storage:
